### ISSUE TITLE
[T5][CLI] manage ads

### ISSUE THREAD

**Issue by rl3250** [howieraem/COMS4156-ASE#61]
### TODO

- [x] inject ads controller
- [ ] update feed after injection ads
- [ ] refactor for reuse react components
