### ISSUE TITLE
[DO_NOT_DELETE] Tracker for T5

### ISSUE THREAD

**Issue by rl3250** [howieraem/COMS4156-ASE#72]
### About this
A simple tracker to maintain todos across our two repos, i know we can use a GH project instead, but this is easy to use.

### Instructions on using this Tracker
1. add a new item when you find one.
2. if you are owning the item, add `@yourself` in the front of the item.
3. once done, cross it out with a PR number

### TODOs

- [x] do we have this? "Implement system tests that exercise your server's final API, e.g., using some API testing tool.  Your tests should exercise the multiple clients and persistent data aspects of your server.  All your API tests should run automatically during CI.  "
- [x] manual e2e tests from client to server; document the tests
- [x] @KenXiong123 client - request page 
- [x] @jenniferduan45  client - transfer page
- [x] client "Describe how some third-party could develop and run their own client that uses your server.  "
- [x] @rl3250 update server readme to include pointer to client repo
- [x] add more instructions on reading the branch & overall coverage badges in readme, CI report
- [x] static code analyzer, should also run during CI - "You should also use a static analysis bug finder tool on your entire server codebase.  The static analyzer should run automatically during CI.  Include the static analysis reports in your server repository.  Try to fix most of the bugs found by the analyzer. "
- [x] @howieraem  client - profile page
